language: cpp
sudo: required
dist: trusty
addons:
    apt:
        sources:
          # add PPAs with more up-to-date toolchains
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          # install toolchains
          - gcc-5
          - g++-5
          - clang-3.6
          - lcov
env:
  - CODECOV_TOKEN="f9bb29da-ad96-4925-b0a9-621a82135e73"

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

install:
  - sudo apt-get install lcov


script:
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON ..
  - make
  - ctest --output-on-failure


after_success:
  # Create lcov report
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info
    # Uploading to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
